# AuditLuma Web配置文件

# 认证模式: login(登录模式) 或 noauth(非登录模式)
auth_mode: login

# 数据库配置 (仅在auth_mode=login时使用)
database:
  # MySQL数据库配置
  host: localhost
  port: 3306
  username: root
  password: password
  database: auditluma
  
# Redis配置 (用于会话管理)
redis:
  host: localhost
  port: 6379
  password: ''
  db: 0

# API配置
api:
  base_url: http://localhost:8000/api
  timeout: 30  # 请求超时时间(秒)

# 系统配置
system:
  log_level: info
  debug: false
  session_timeout: 3600  # 会话超时时间(秒)
